<?php

return [
    'reviews' => [
        // Any detected violation is directly set to pending.
        // Scoring is not used for decision-making in this mode.
        'pending_threshold' => 1,
        'reject_threshold' => 999,

        // Extended blocked words list (Arabic/English + common variants).
        'blocked_words' => [
            // Arabic insults/profanity (common)
            'شتيمة',
            'سب',
            'قذر',
            'حقير',
            'تافه',
            'سخيف',
            'غبي',
            'احمق',
            'حيوان',
            'كلب',
            'خنزير',
            'نجس',
            'تفو',
            'تباً',
            'تبا',
            'يلعن',
            'لعنة',
            'انعل',
            'انقلع',
            'انطم',
            'اخرس',
            'اخرسي',
            'كذاب',
            'كذابة',
            'نصاب',
            'حرامي',
            'حرامية',
            'قحبة',
            'شرموطة',
            'شرموط',
            'زانية',
            'زاني',
            'ابن الكلب',
            'يا كلب',
            'يا حيوان',
            'يا حمار',
            'حمار',
            'حيوانه',
            'معفن',
            'وسخ',
            'وصخ',
            'مقرف',
            'منحط',
            'قليل ادب',
            'قليل الادب',
            'عديم ادب',
            'عديم الادب',
            'يا عرص',
            'عرص',
            'خول',
            'متخلف',
            'مريض',

            // English profanity/insults
            'fuck',
            'fucking',
            'fucker',
            'motherfucker',
            'shit',
            'bullshit',
            'bitch',
            'bastard',
            'asshole',
            'dumbass',
            'idiot',
            'stupid',
            'moron',
            'retard',
            'jerk',
            'loser',
            'trash',
            'scum',
            'slut',
            'whore',
            'pimp',
            'dick',
            'cock',
            'pussy',
            'bitches',
            'f u c k',
            'f*ck',
            'sh!t',
            'a55hole',

            // Arabizi/common transliteration
            'zeb',
            'kos',
            'sharmota',
            'kahba',
            'ibn kalb',
            'ya kalb',
            'ya 7mar',
            '7mar',

            // Iraqi dialect (common insults/profanity variants)
            'كلخرا',
            'كل خرا',
            'خرا',
            'خره',
            'ابن الخرا',
            'ابن خرا',
            'ابو خرا',
            'كس اختك',
            'كس امك',
            'كس اخت',
            'زب',
            'زبي',
            'زق',
            'زقنبوت',
            'طيز',
            'طيزك',
            'مطيرجي',
            'قندرة',
            'منيوج',
            'منيوكة',
            'منحرف',
            'نذل',
            'واطي',
            'واطيه',
            'نعل',
            'نعال',
            'نعال ابو',
            'انجب',
            'جلب',
            'يا جلب',
            'حيوان انت',
            'جبان',
            'جبانين',
            'تفو عليك',
            'الله ياخذك',
            'الله لا يوفقك',
            'انقلع من هنا',
            'كلب ابن كلب',

            // Iraqi Arabizi variants
            'kl khra',
            'khra',
            '5ra',
            'zebi',
            'kss omk',
            'kss okhtk',
            'ya glb',
            'glb',
            'wa6i',
            'wa6ya',
            'mnioj',
            'mnioja',
        ],

        // Common short-link domains often used in spam.
        'shortener_domains' => [
            'bit.ly',
            'tinyurl.com',
            't.co',
            'goo.gl',
            'is.gd',
            'cutt.ly',
            'shorturl.at',
        ],

        // Optional external moderation API.
        // Keep disabled unless a provider is configured.
        'external_api' => [
            'enabled' => env('REVIEW_MODERATION_API_ENABLED', false),
            'url' => env('REVIEW_MODERATION_API_URL', ''),
            'token' => env('REVIEW_MODERATION_API_TOKEN', ''),
            'timeout_seconds' => (int) env('REVIEW_MODERATION_API_TIMEOUT', 5),

            // Supported payloads: default | openai_like | perspective_like
            'payload_mode' => env('REVIEW_MODERATION_API_PAYLOAD_MODE', 'default'),

            // Optional custom headers map.
            'headers' => [],
        ],
    ],
];
